#!/bin/sh
set -e
package_name=discover-biglinux
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.kde.discover.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/flatpak-backend-categories.xml"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/packagekit-backend-categories.xml"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/snap-backend-categories.xml"
    
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.kde.discover.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/flatpak-backend-categories.xml"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/packagekit-backend-categories.xml"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/libdiscover/categories/snap-backend-categories.xml"
;;
esac
exit 0
