#!/bin/sh
set -e
package_name=discover-biglinux
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.kde.discover.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.kde.discover.desktop"
;;
esac
exit 0
